using Futurum.WebApiEndpoint.Micro.Generator.Core;

namespace Futurum.WebApiEndpoint.Micro.Generator;

public static class SourceGeneratorWriter
{
    public static IndentedStringBuilder Write(string assemblyName, string methodName)
    {
        var codeBuilder = new IndentedStringBuilder();

        codeBuilder
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine();

        codeBuilder
            .AppendLine($"namespace {assemblyName}")
            .AppendLine("{")
            .IncrementIndent();

        codeBuilder
            .Append("[global::System.CodeDom.Compiler.GeneratedCode(\"")
            .Append(ThisAssembly.Project.AssemblyName)
            .Append("\", \"")
            .Append(ThisAssembly.Info.Version)
            .AppendLine("\")]");

        codeBuilder
            .AppendLine("[global::System.Diagnostics.DebuggerNonUserCodeAttribute]")
            .AppendLine("[global::System.Diagnostics.DebuggerStepThroughAttribute]")
            .AppendLine($"public static partial class {methodName}Extensions")
            .AppendLine("{")
            .IncrementIndent()
            .Append("public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection")
            .Append(" Add")
            .Append("WebApiEndpointsFor")
            .Append(methodName)
            .AppendLine("(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection serviceCollection)")
            .AppendLine("{")
            .IncrementIndent();

        codeBuilder.AppendLine("serviceCollection.RegisterWebApiEndpoints();");
        codeBuilder.AppendLine("serviceCollection.RegisterFluentValidators();");

        codeBuilder
            .AppendLine("return serviceCollection;")
            .DecrementIndent()
            .AppendLine("}") // method
            .DecrementIndent()
            .AppendLine("}") // class
            .DecrementIndent()
            .AppendLine("}"); // namespace
        
        return codeBuilder;
    }
}